keys:
  - &yubikey_alpha 7A5FB73E81C9215C692D994349E1D3136F71FED7
    # nix-shell -p ssh-to-age --run 'ssh-keyscan reaper.lan | ssh-to-age'
  - &reaper_host age1d3hhj0tzjrqt7w5nzqx86fha5cemmgdn99n5v2aw76ut7ucp8vyqspxyhn
    # nix-shell -p ssh-to-age --run 'ssh-keyscan hoard.lan | ssh-to-age'
  - &hoard_host age1ae5trkyduadhc45d90svq9yem62fhj676m4jyapplcsrjq78tf2qtk2yuw
    # nix-shell -p ssh-to-age --run 'ssh-keyscan harbor.lan | ssh-to-age'
  - &harbor_host age142kp0x4azfwvmxe0drmpt0lug4upj22wahefsezrcv3nvmcgkeds74jeld
creation_rules:
  - path_regex: secrets/common/.*\.yaml$
    key_groups:
      - age:
          - *reaper_host
          - *hoard_host
          - *harbor_host
        pgp:
          - *yubikey_alpha

  - path_regex: secrets/reaper/.*\.yaml$
    key_groups:
      - age:
          - *reaper_host
        pgp:
          - *yubikey_alpha

  - path_regex: secrets/hoard/.*\.yaml$
    key_groups:
      - age:
          - *hoard_host
        pgp:
          - *yubikey_alpha
  - path_regex: secrets/harbor/.*\.yaml$
    key_groups:
      - age:
          - *harbor_host
        pgp:
          - *yubikey_alpha
