[formatter.nixfmt]
command = "nixfmt"
includes = ["*.nix"]

[formatter.stylua]
command = "stylua"
includes = ["*.lua"]

[formatter.shfmt]
command = "shfmt"
options = ["-i", "2", "-w"]
includes = ["*.sh", "*.bash"]

[formatter.taplo]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.ruff-format]
command = "ruff"
options = ["format"]
includes = ["*.py"]
