{
  imports = [
    ../../common
    ../common
    ./acme.nix
    ./build-server.nix
    ./disk-spindown.nix
    ./duckdns.nix
    ./cloudflare-ddns.nix
    ./glances.nix
    ./machine-id.nix
    ./ollama.nix
    ./qbittorrent.nix
    ./rustdesk.nix
    ./sabnzbd.nix
    ./tailscale.nix
    ./terminfo.nix
    ./gatus-path-check.nix
  ];
}
