cloudflare_zone_id: ENC[AES256_GCM,data:cFPecPyKA7JDJXGQUUmAZyih0J3DW+xjVBMtVKnGxJA=,iv:Z4JoWx5EE9AYwpIcpOycu6zrDO6BSfBAF1fh+2AaMp8=,tag:+YoWu3pmOQTwwu5bH1J/rA==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:Pww8sDwjJS/VJ0IhTApgdzuxdgxlXuoN2tpnCnmWulnsyTh6FCVVnw==,iv:LcUNSFUGUTshMA+BhWepfVcgcbJcRJUyMJhQpkOMf68=,tag:pQuurcLVLjBAAYqsefELsQ==,type:str]
sops:
    age:
        - recipient: age17h86yfzhhn47lnp64r4szyu2dwd6gwt7nxwy3hlcuuq06ycd3slsh580m4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWWd3K2dGNTRFVnJISEVo
            dXpqcEQvay9EZ2lFQ2g5aEVkOEN5aU10VVhBCnowN2Q5NDY3SG9LNTVZOEFob1FL
            a3RlQW1EcGJ2SzRLMVc2UXdIZ1p2VlUKLS0tIFl6N3laTmRmRTF2TzhjZnpNZVVj
            WXhhNVNkRUFzb2Y0Y3V4MG0rYzdxL3MK0pQe5a67FxhLHBC88ILa8XkZcB/qUt9S
            pQCUdbICynN615kbVryLuYSNRUApu9haEUk9e6SEOuiY4ndiVtbzQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1d3hhj0tzjrqt7w5nzqx86fha5cemmgdn99n5v2aw76ut7ucp8vyqspxyhn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTakZXVUNza09QR0FrUW1V
            OUlnYjF3cUg2eUc0ZXI2VUxINWxLLzA5TFdBCnhJcVIrWTN3S09hbVM5c2Rnb3Jv
            SGY5ZlRrT0U3Zzg1aEVVZlJQRElhRmsKLS0tIGpLaHZ6NWVtVmllbkQrWFNodXpr
            RXVaUGpyd1pSM0FHQVhxdUt2Y0h3MlEKNkcLqKoPLclFqElXCUml6fL4IjvR+lL7
            PE5GO1IrY7UsAHFsEAUYNYVr5M7cozB39xmGLRxAJ/oBrZcpJGlMtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ae5trkyduadhc45d90svq9yem62fhj676m4jyapplcsrjq78tf2qtk2yuw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3BHRUlXeFhYVHczRjVB
            UXFVK1llbVFIUmg0dnVwQkViOENrNjE0M1NnCmxjckRTM0lZSk8rbDVRNzFXYW5U
            SzloU0k4ZUJMMjFBR0dmNjRReERPWWMKLS0tIElWbkZlaC8zYTZPZGxsbGNjZXZ6
            cHV1R283MURkMVEwa2lHSWV1TGVOSjQKnQcrtr33C27AL9Kqw1m3D6+5AAD3hv9f
            pbz7SAD/VnjWeOfBoB1Cf4uzzJAG20HCHid32toxEBBV+ZGuLJP6bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T18:04:13Z"
    mac: ENC[AES256_GCM,data:VpLgHVMyR/23jzp/pd+6NpE5xJiTqQ9r+PZ6f39i9UH/fJNcgqq/IO+/BxzsTsGrPaWxwfrcie8QUMRU4ql6HTMflLWuFWBsJAyedRy4ALYf6qQyxTafoRqddO8SqKmzUS44FTGvUajxg3YhkjrfDyO1LStsK1Agd5tKI9YSpT8=,iv:NyA1mdLBKuxxzJV8G4UUCUVL/EdYhupJMDpicussCwQ=,tag:t4bISrRZBMqYjFwwArZIDg==,type:str]
    pgp:
        - created_at: "2025-12-10T18:04:13Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA0nh0xNvcf7XAQf/brR+iLY/yO+kNX37vzw9PcWPgxP5PNbaBP8lw2xB0ORP
            yVzEUyDjAOYAHJGD+V2xssLVhlHVhk+hcu96ym+AbNA1O/ZZtwO0rMWruzt7zw+k
            0LlZznF9vBwDPWRqewxOVooxaaosYy9VFcE9xtorMyjqUwDRoQ9k9zWW5LyGLV/U
            hoMzl+m3zRIvHav4LZxfjNBVa5qtNvzNVdbXQys4a4Q+bKmnE+LhQ469jMs6j4h7
            7T2Lm/RJV1oHr5Wb0/URVPAvbd2scOPoIX2q3WruB1qq6y+/Ic2CEe6OC6ItTR2h
            m8Olg7jGmllfRDRrIAP56cz97P5Ueuu0NzcVU1vyOdJbAbV+sUHeOO7maYDLDfvV
            WHdsQqirdZ0NJD5MEKDpHzJijMJ8Znph7EnEUJmyeshbNmTkICUoMoWn4/cvHGnK
            8+InXMm4lAf88FkoOZcR81q/HL2Bj63xlPrPTw==
            =RuH8
            -----END PGP MESSAGE-----
          fp: 7A5FB73E81C9215C692D994349E1D3136F71FED7
    unencrypted_suffix: _unencrypted
    version: 3.11.0
